export const commonApiPaths = {
  wxAutoReply: 'POST /api/so/common/wx_auto_reply',
  wxUpload: 'POST /api/so/common/wx_upload',
  getWxAccessToken: 'GET /api/so/common/wx_access_token',
  mpQrcode: 'POST /api/so/common/mp_qrcode',
  mpQrcodeJson: 'POST /api/so/common/mp_qrcode_json',
  getAccessTokenByIdSecret: 'POST /api/so/common/get_access_token_by_id_secret',
  clearQuota: 'GET /api/so/common/clear_quota',
  getSystemInfo: 'GET /api/so/common/system/get',
  updateSystemInfo: 'POST /api/so/common/system/update',
  hotArticleComment: 'POST /api/so/common/csdn/hot_article_comment',
  getCsdnConfig: 'GET /api/so/common/csdn/config/get',
  updateCsdnConfig: 'POST /api/so/common/csdn/config/update',
  triggerComment: 'POST /api/so/common/csdn/trigger_comment',
  getAiReply: 'POST /api/so/common/ai/reply',
  aiReplyMemoryErasure: 'POST /api/so/common/ai/reply/memory_erasure',
  getAiWechatArticleReply: 'POST /api/so/common/ai/wechat_article',
  aiReplyStream: 'POST /api/so/common/ai/reply/stream',
  parseWebView: 'GET /api/so/common/web_view/parse',
  getHotData: 'GET /api/so/common/hot_data/get',
  getFeRedis: 'GET /api/so/common/fe_redis/get',
  setFeRedis: 'POST /api/so/common/fe_redis/set',
  delFeRedis: 'POST /api/so/common/fe_redis/del',
  getUserBehaviorStats: 'GET /api/so/common/user_behavior_stats',
} as const

export type {
  AutoReplyReq,
  AutoReplyResp,
  WxUploadResp,
  MpQrcodeReq,
  MpQrcodeResp,
  GetWxAccessTokenResp,
  GetAccessTokenByIdSecretReq,
  GetAccessTokenByIdSecretResp,
  ClearQuotaResp,
  LinkMenu,
  SystemInfoView,
  UpdateSystemInfoReq,
  CsdnCommentReq,
  GetCsdnConfigResp,
  UpdateCsdnConfigReq,
  TriggerCommentReq,
  AiReplyReq,
  AiReplyResp,
  AiReplyMemoryErasureReq,
  AiReplyMemoryErasureResp,
  AiWechatArticleReq,
  AiWechatArticleResp,
  AiReplyStreamResp,
  ParseWebViewReq,
  ParseWebViewResp,
  GetHotDataReq,
  HotDataView,
  GetHotDataResp,
  GetFeRedisReq,
  GetFeRedisResp,
  SetFeRedisReq,
  DelFeRedisReq,
  GetUserBehaviorStatsReq,
  TableStats,
  DayStats,
  GetUserBehaviorStatsResp,
} from '../types/api/common'
