export const tripApiPaths = {
  createTrip: 'POST /api/so/trip/create',
  updateTrip: 'POST /api/so/trip/update',
  deleteTrip: 'POST /api/so/trip/delete',
  getTripDetail: 'GET /api/so/trip/detail',
  getTripList: 'POST /api/so/trip/list',
  planTripStream: 'GET /api/so/trip/plan/stream',
  planTripStreamV2: 'GET /api/so/trip/plan/stream/v2',
  createTripSpot: 'POST /api/so/trip/spot/create',
  updateTripSpot: 'POST /api/so/trip/spot/update',
  deleteTripSpot: 'POST /api/so/trip/spot/delete',
  getTripSpotList: 'GET /api/so/trip/spot/list',
  batchUpdateTripSpotSort: 'POST /api/so/trip/spot/batch_update_sort',
} as const

export type {
  TripStatus,
  TravelPreference,
  CreateTripSpotItem,
  TripDetail,
  TripListItem,
  TripSpotDetail,
  TripSpotListItem,
  GetTripListReq,
  GetTripListResp,
  GetTripDetailReq,
  GetTripDetailResp,
  CreateTripReq,
  CreateTripResp,
  UpdateTripReq,
  UpdateTripResp,
  DeleteTripReq,
  DeleteTripResp,
  GetTripSpotListReq,
  GetTripSpotListResp,
  CreateTripSpotReq,
  CreateTripSpotResp,
  UpdateTripSpotReq,
  UpdateTripSpotResp,
  DeleteTripSpotReq,
  DeleteTripSpotResp,
  BatchUpdateTripSpotSortReq,
  BatchUpdateTripSpotSortResp,
  PlanTripReq,
  PlanTripSpotItem,
  PlanTripStreamV2Item,
  SpotListItem,
} from '../types/api/trip'
