export const userApiPaths = {
  getCode: 'GET /api/so/user/code',
  setJwt: 'POST /api/so/user/set_jwt',
  getJwt: 'GET /api/so/user/get_jwt',
  login: 'GET /api/so/user/login',
  getUser: 'GET /api/so/user/get',
  getByOpenid: 'GET /api/so/user/get_by_openid',
  getUserList: 'GET /api/so/user/list',
  updateUser: 'POST /api/so/user/update',
  getSubUser: 'GET /api/so/user/sub/get',
  addSubUser: 'POST /api/so/user/sub/add',
  delSubUser: 'POST /api/so/user/sub/del',
  generateAccount: 'GET /api/so/user/account/generate',
  registerAccount: 'POST /api/so/user/account/register',
  checkAccount: 'GET /api/so/user/account/check',
  subscribeMsg: 'POST /api/so/user/message/sub',
} as const

export type {
  GetCodeReq,
  GetCodeResp,
  SetJwtReq,
  SetJwtResp,
  GetJwtReq,
  GetJwtResp,
  LoginReq,
  LoginResp,
  GetUserReq,
  GetUserResp,
  GetByOpenidReq,
  GetByOpenidResp,
  GetUserListReq,
  GetUserListResp,
  UpdateUserReq,
  GetSubUserReq,
  GetSubUserResp,
  AddSubUserReq,
  DelSubUserReq,
  GenerateAccountReq,
  GenerateAccountResp,
  RegisterAccountReq,
  RegisterAccountResp,
  CheckAccountReq,
  CheckAccountResp,
  SubscribeMsgReq,
} from '../types/api/user'
